# Generated by Django 2.2.1 on 2019-05-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20190520_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.IntegerField(choices=[(1, 'Choose'), (2, 'Photographer'), (3, 'Florist'), (4, 'Cake'), (5, 'Catering'), (6, 'Clothing'), (7, 'Dj'), (8, 'Venue')], default=1),
        ),
    ]
