# Generated by Django 2.2.1 on 2019-05-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='purpose',
            field=models.IntegerField(default=1),
        ),
    ]
