# Generated by Django 2.2.1 on 2019-05-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20190517_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendors',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='vendors',
            name='last_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendors',
            name='purpose',
            field=models.IntegerField(blank=True, choices=[(1, 'Venue'), (2, 'Photographer'), (3, 'Florist'), (4, 'Cake'), (5, 'Catering'), (6, 'Clothing'), (7, 'Dj')]),
        ),
    ]
