# Generated by Django 2.2.1 on 2019-05-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20190518_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='last_name',
        ),
    ]
