# Generated by Django 2.2.1 on 2019-05-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20190518_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='purpose',
            field=models.IntegerField(choices=[(1, 'Choose'), (2, 'Photographer'), (3, 'Florist'), (4, 'Cake'), (5, 'Catering'), (6, 'Clothing'), (7, 'Dj'), (8, 'Venue')], default=1),
        ),
    ]
